export const environment = {
  production: false,
  appName: "LMS",
  appUrl: "http://localhost:3000",
  appPrefix: "api",
  appKey: "secret",
  jwtTtl: 86400,
  appVersion: '1.0',
  dbLog: true,
  migrationsRun: false,
  dbConnection: 'mysql',
  dbHost: 'localhost',
  dbPort: 30000,
  dbName: 'lms',
  dbUser: 'root',
  dbPass: 'secret',
  enableLoginFailedCheck: true,
  maxLoginFailed: 10,
  maxFileUploadAllowed: 10,
  smtpUser: 'no-reply@vicoders.com',
  smtpPass: '',
  smtpHost: 'smtp.mandrillapp.com',
  smtpPort: '587',
};
