import {
  APP_BASE_HREF,
  CommonModule,
} from '@angular/common';
import { RouterModule } from '@angular/router';

import { NzBreadCrumbModule } from 'ng-zorro-antd/breadcrumb';

import {
  Meta,
  moduleMetadata,
  Story,
} from '@storybook/angular';

import { BreadcrumbComponent } from './breadcrumb.component';

export default {
  title: 'Breadcrumb',
  decorators: [
    moduleMetadata({
      imports: [
        CommonModule,
        RouterModule.forRoot([{ path: '', loadChildren: () => import('../dummy/dummy.module').then(m => m.DummyModule) }], { useHash: true }),
        NzBreadCrumbModule
      ],
      providers: [{ provide: APP_BASE_HREF, useValue: '/' }]
    })
  ],
} as Meta<BreadcrumbComponent>;

const Template: Story<BreadcrumbComponent> = (args: BreadcrumbComponent) => ({
  component: BreadcrumbComponent,
  props: args,
});


export const Primary = Template.bind({});
Primary.args = {
  items: [
    { label: 'Home', routerLink: ['/'] },
    { label: 'User', routerLink: ['/', 'users'] },
    { label: 'Detail' }
  ],
}
Primary.parameters = {
  docs: { inlineStories: true, }
}

export const AutoGenerated = Template.bind({});
AutoGenerated.args = {
  nzAutoGenerate: true
}
AutoGenerated.parameters = {
  docs: { inlineStories: true, }
}
