export const environment = {
  production: false,
  siteTitle: 'Anime Online',
  enableSentry: false,
  sentryDsn: '',
  sentryEnvironment: 'dev',
  tracesSampleRate: 0.1,
  enableMockApi: false,
  tokenKey: 'token',
  apiUrl: 'http://localhost:3000/api',
  languageLocalStorageKey: 'lang',
  availabelLanguages: ['vi', 'en'],
  defaultLanguage: 'vi',
  fbMessengerEnable: true,
};
