export const environment = {
  production: true,
  siteTitle: 'ÔN THI CÔNG CHỨC 247',
  siteDescription: 'Công chức 247 cung cấp các khóa ôn thi công chức, viên chức ngành dọc của Tổng cục Thuế, Kho bạc Nhà nước, Tổng cục Hải quan, Tổng cục Thống kê,... chất lượng hàng đầu Viêt Nam',
  enableSentry: false,
  sentryDsn: '',
  sentryEnvironment: 'production',
  tracesSampleRate: 0.1,
  enableMockApi: false,
  tokenKey: 'token',
  apiUrl: 'https://online.congchuc247.vn/api',
  languageLocalStorageKey: 'lang',
  availabelLanguages: ['vi', 'en'],
  defaultLanguage: 'vi',
  fbMessengerEnable: true,
};
