import { environment } from './../../../../common/src/environments/environment';
import {
  MigrationInterface,
  QueryRunner,
} from 'typeorm';

export class CourseTableSeeder1650531111059 implements MigrationInterface {

  public async up(queryRunner: QueryRunner): Promise<void> {
    const items = [
      {
        name: 'KTC TỔNG QUÁT - CÔNG CHỨC KHO BẠC 2021',
        lecturer: 'Thầy Tài Tân Tiến',
        categoryId: 1,
        image: `${environment.appUrl}/uploads/kho-bac@2x.png`,
        video: 'AMEI1XY8pH4',
        description: 'Xua tan nỗi sợ “học trước quên sau” với phương pháp ghi nhớ liên tưởng kết hợp với chuyện chêm giúp làm trắc nghiệm nhanh, chính xác đã được kiểm chứng bởi hàng trăm người.',
        isFreeCourse: false,
        originalPrice: 5000000,
        price: 4590000,
        status: 1,
        rateCount: 15,
        rateAverage: 4.5,
      },
      {
        name: 'KTC TỔNG QUÁT - QUẢN LÝ THỊ TRƯỜNG 2021',
        lecturer: 'Thầy Tài Tân Tiến',
        categoryId: 1,
        image: `${environment.appUrl}/uploads/quan-ly-thi-truong@2x.png`,
        video: 'AMEI1XY8pH4',
        description: 'Xua tan nỗi sợ “học trước quên sau” với phương pháp ghi nhớ liên tưởng kết hợp với chuyện chêm giúp làm trắc nghiệm nhanh, chính xác đã được kiểm chứng bởi hàng trăm người.',
        isFreeCourse: false,
        originalPrice: 5000000,
        price: 4590000,
        status: 1,
        rateCount: 15,
        rateAverage: 4.5,
      },
      {
        name: 'KTC TỔNG QUÁT - CÔNG THỨC THUẾ 2021',
        lecturer: 'Thầy Tài Tân Tiến',
        categoryId: 1,
        image: `${environment.appUrl}/uploads/thue@2x.png`,
        video: 'AMEI1XY8pH4',
        description: 'Xua tan nỗi sợ “học trước quên sau” với phương pháp ghi nhớ liên tưởng kết hợp với chuyện chêm giúp làm trắc nghiệm nhanh, chính xác đã được kiểm chứng bởi hàng trăm người.',
        isFreeCourse: false,
        originalPrice: 5000000,
        price: 4590000,
        status: 1,
        rateCount: 15,
        rateAverage: 4.5,
      },
      {
        name: 'KTC TỔNG QUÁT - CÔNG CHỨC KHO BẠC 2021',
        lecturer: 'Thầy Tài Tân Tiến',
        categoryId: 1,
        image: `${environment.appUrl}/uploads/kho-bac@2x.png`,
        video: 'AMEI1XY8pH4',
        description: 'Xua tan nỗi sợ “học trước quên sau” với phương pháp ghi nhớ liên tưởng kết hợp với chuyện chêm giúp làm trắc nghiệm nhanh, chính xác đã được kiểm chứng bởi hàng trăm người.',
        isFreeCourse: false,
        originalPrice: 5000000,
        price: 4590000,
        status: 1,
        rateCount: 15,
        rateAverage: 4.5,
      },
      {
        name: 'KTC TỔNG QUÁT - QUẢN LÝ THỊ TRƯỜNG 2021',
        lecturer: 'Thầy Tài Tân Tiến',
        categoryId: 1,
        image: `${environment.appUrl}/uploads/quan-ly-thi-truong@2x.png`,
        video: 'AMEI1XY8pH4',
        description: 'Xua tan nỗi sợ “học trước quên sau” với phương pháp ghi nhớ liên tưởng kết hợp với chuyện chêm giúp làm trắc nghiệm nhanh, chính xác đã được kiểm chứng bởi hàng trăm người.',
        isFreeCourse: false,
        originalPrice: 5000000,
        price: 4590000,
        status: 1,
        rateCount: 15,
        rateAverage: 4.5,
      },
      {
        name: 'KTC TỔNG QUÁT - CÔNG THỨC THUẾ 2021',
        lecturer: 'Thầy Tài Tân Tiến',
        categoryId: 1,
        image: `${environment.appUrl}/uploads/thue@2x.png`,
        video: 'AMEI1XY8pH4',
        description: 'Xua tan nỗi sợ “học trước quên sau” với phương pháp ghi nhớ liên tưởng kết hợp với chuyện chêm giúp làm trắc nghiệm nhanh, chính xác đã được kiểm chứng bởi hàng trăm người.',
        isFreeCourse: false,
        originalPrice: 5000000,
        price: 4590000,
        status: 1,
        rateCount: 15,
        rateAverage: 4.5,
      },
      {
        name: 'KTC TỔNG QUÁT - CÔNG CHỨC KHO BẠC 2021',
        lecturer: 'Thầy Tài Tân Tiến',
        categoryId: 1,
        image: `${environment.appUrl}/uploads/kho-bac@2x.png`,
        video: 'AMEI1XY8pH4',
        description: 'Xua tan nỗi sợ “học trước quên sau” với phương pháp ghi nhớ liên tưởng kết hợp với chuyện chêm giúp làm trắc nghiệm nhanh, chính xác đã được kiểm chứng bởi hàng trăm người.',
        isFreeCourse: false,
        originalPrice: 5000000,
        price: 4590000,
        status: 1,
        rateCount: 15,
        rateAverage: 4.5,
      },
      {
        name: 'KTC TỔNG QUÁT - QUẢN LÝ THỊ TRƯỜNG 2021',
        lecturer: 'Thầy Tài Tân Tiến',
        categoryId: 1,
        image: `${environment.appUrl}/uploads/quan-ly-thi-truong@2x.png`,
        video: 'AMEI1XY8pH4',
        description: 'Xua tan nỗi sợ “học trước quên sau” với phương pháp ghi nhớ liên tưởng kết hợp với chuyện chêm giúp làm trắc nghiệm nhanh, chính xác đã được kiểm chứng bởi hàng trăm người.',
        isFreeCourse: false,
        originalPrice: 5000000,
        price: 4590000,
        status: 1,
        rateCount: 15,
        rateAverage: 4.5,
      },
      {
        name: 'KTC TỔNG QUÁT - CÔNG THỨC THUẾ 2021',
        lecturer: 'Thầy Tài Tân Tiến',
        categoryId: 1,
        image: `${environment.appUrl}/uploads/thue@2x.png`,
        video: 'AMEI1XY8pH4',
        description: 'Xua tan nỗi sợ “học trước quên sau” với phương pháp ghi nhớ liên tưởng kết hợp với chuyện chêm giúp làm trắc nghiệm nhanh, chính xác đã được kiểm chứng bởi hàng trăm người.',
        isFreeCourse: false,
        originalPrice: 5000000,
        price: 4590000,
        status: 1,
        rateCount: 15,
        rateAverage: 4.5,
      },
      {
        name: 'KTC TỔNG QUÁT - CÔNG CHỨC KHO BẠC 2021',
        lecturer: 'Thầy Tài Tân Tiến',
        categoryId: 1,
        image: `${environment.appUrl}/uploads/kho-bac@2x.png`,
        video: 'AMEI1XY8pH4',
        description: 'Xua tan nỗi sợ “học trước quên sau” với phương pháp ghi nhớ liên tưởng kết hợp với chuyện chêm giúp làm trắc nghiệm nhanh, chính xác đã được kiểm chứng bởi hàng trăm người.',
        isFreeCourse: false,
        originalPrice: 5000000,
        price: 4590000,
        status: 1,
        rateCount: 15,
        rateAverage: 4.5,
      },
      {
        name: 'KTC TỔNG QUÁT - QUẢN LÝ THỊ TRƯỜNG 2021',
        lecturer: 'Thầy Tài Tân Tiến',
        categoryId: 1,
        image: `${environment.appUrl}/uploads/quan-ly-thi-truong@2x.png`,
        video: 'AMEI1XY8pH4',
        description: 'Xua tan nỗi sợ “học trước quên sau” với phương pháp ghi nhớ liên tưởng kết hợp với chuyện chêm giúp làm trắc nghiệm nhanh, chính xác đã được kiểm chứng bởi hàng trăm người.',
        isFreeCourse: false,
        originalPrice: 5000000,
        price: 4590000,
        status: 1,
        rateCount: 15,
        rateAverage: 4.5,
      },
      {
        name: 'KTC TỔNG QUÁT - CÔNG THỨC THUẾ 2021',
        lecturer: 'Thầy Tài Tân Tiến',
        categoryId: 1,
        image: `${environment.appUrl}/uploads/thue@2x.png`,
        video: 'AMEI1XY8pH4',
        description: 'Xua tan nỗi sợ “học trước quên sau” với phương pháp ghi nhớ liên tưởng kết hợp với chuyện chêm giúp làm trắc nghiệm nhanh, chính xác đã được kiểm chứng bởi hàng trăm người.',
        isFreeCourse: false,
        originalPrice: 5000000,
        price: 4590000,
        status: 1,
        rateCount: 15,
        rateAverage: 4.5,
      },
      {
        name: 'KTC TỔNG QUÁT - CÔNG CHỨC KHO BẠC 2022',
        lecturer: 'Thầy Tài Tân Tiến',
        categoryId: 1,
        image: `${environment.appUrl}/uploads/kho-bac@2x.png`,
        video: 'AMEI1XY8pH4',
        description: 'Xua tan nỗi sợ “học trước quên sau” với phương pháp ghi nhớ liên tưởng kết hợp với chuyện chêm giúp làm trắc nghiệm nhanh, chính xác đã được kiểm chứng bởi hàng trăm người.',
        isFreeCourse: true,
        originalPrice: 0,
        price: 0,
        status: 1,
        rateCount: 15,
        rateAverage: 4.5,
      },
      {
        name: 'KTC TỔNG QUÁT - QUẢN LÝ THỊ TRƯỜNG 2022',
        lecturer: 'Thầy Tài Tân Tiến',
        categoryId: 1,
        image: `${environment.appUrl}/uploads/quan-ly-thi-truong@2x.png`,
        video: 'AMEI1XY8pH4',
        description: 'Xua tan nỗi sợ “học trước quên sau” với phương pháp ghi nhớ liên tưởng kết hợp với chuyện chêm giúp làm trắc nghiệm nhanh, chính xác đã được kiểm chứng bởi hàng trăm người.',
        isFreeCourse: true,
        originalPrice: 0,
        price: 0,
        status: 1,
        rateCount: 15,
        rateAverage: 4.5,
      },
      {
        name: 'KTC TỔNG QUÁT - CÔNG THỨC THUẾ  2022',
        lecturer: 'Thầy Tài Tân Tiến',
        categoryId: 1,
        image: `${environment.appUrl}/uploads/thue@2x.png`,
        video: 'AMEI1XY8pH4',
        description: 'Xua tan nỗi sợ “học trước quên sau” với phương pháp ghi nhớ liên tưởng kết hợp với chuyện chêm giúp làm trắc nghiệm nhanh, chính xác đã được kiểm chứng bởi hàng trăm người.',
        isFreeCourse: true,
        originalPrice: 0,
        price: 0,
        status: 1,
        rateCount: 15,
        rateAverage: 4.5,
      },
    ];

    const query = queryRunner.manager.createQueryBuilder()
      .insert()
      .into('course')


    for (const item of items) {
      await query.values(item).execute();
    }

  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.clearTable('course');
  }

}
